namespace JJones.IPASimulator.Model.MachO
{
    public enum LoadCommandType : uint
    {
        Segment = 1,
        Symtab,
        Symseg,
        Thread,
        Unixthread,
        LoadFVMLib,
        IdFVMLib,
        Ident,
        FVMFile,
        Prepage,
        DySymTab,
        LoadDylib,
        IdDylib,
        LoadDyLinker,
        IdDyLinker,
        PreboundDylib,
        Routines,
        SubFramework,
        SubUmbrella,
        SubClient,
        SubLibrary,
        TwoLevelHints,
        PrebindCksum,
        LoadWeakDylib = 0x18 | LoadCommandMask.ReqDyld,
        Segment64 = 0x19,
        Routines64,
        Uuid,
        Rpath = 0x1C | LoadCommandMask.ReqDyld,
        CodeSignature = 0x1D,
        SegmentSplitInfo,
        ReexportDylib,
        LazyLoadDylib,
        EncryptionInfo,
        DyldInfo,
        DyldInfoOnly = 0x22 | LoadCommandMask.ReqDyld,
        LoadUpwardDylib = 0x23 | LoadCommandMask.ReqDyld,
        VersionMinMacOsX = 0x24,
        VersionMinIPhoneOs,
        FunctionStarts,
        DyldEnvironment,
        Main = 0x28 | LoadCommandMask.ReqDyld,
        DataInCode = 0x29,
        SourceVersion,
        DylibCodeSignDRs,
        EncryptionInfo64,
        LinkerOption,
        LinkerOptimizationHint,
        VersionMinTvOs,
        VersionMinWatches
    }
}
